#!/usr/bin/env bash
# install the ufw firewall and setup a few rules
sudo apt-get install ufw -y 
sudo ufw default deny incoming 
sudo ufw allow 80 
sudo ufw allow 22 
sudo ufw allow 443
sudo ufw enable 
